/*
 * Copyright (C) 2015 carcasti
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.client.ui;


import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.ClientController;


/**
 *
 * @author carcasti
 */
public class ClientUIOld extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ClientUI
     */
    private  ImageIcon icon;
    JFileChooser fc;
    ClientController clientController;
   
    public ClientUIOld() {
        initComponents();
        
        fc = new JFileChooser();
        //Btns
        btnAdd.addActionListener(this);
        btnEdit.addActionListener(this);
        btnSave.addActionListener(this);
        btnLibrary.addActionListener(this);
        btnExit.addActionListener(null);
        btnLoad.addActionListener(this);
 
        this.setLocationRelativeTo(null);
        clientController = new ClientController(1520);
        clientController.setTarget_port(port);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        loadedImage = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLibrary = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Filter Express");
        setName("clienteUiForm"); // NOI18N
        setSize(new java.awt.Dimension(650, 600));
        getContentPane().setLayout(null);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Add.png"))); // NOI18N
        btnAdd.setToolTipText("Add image");
        btnAdd.setActionCommand("btnLoad");
        btnAdd.setPreferredSize(new java.awt.Dimension(60, 60));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(20, 240, 60, 60);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Modify.png"))); // NOI18N
        btnEdit.setToolTipText("Edit Image");
        btnEdit.setPreferredSize(new java.awt.Dimension(60, 60));
        btnEdit.setSize(new java.awt.Dimension(60, 60));
        getContentPane().add(btnEdit);
        btnEdit.setBounds(20, 310, 60, 60);

        loadedImage.setBackground(new java.awt.Color(0, 153, 153));
        loadedImage.setToolTipText("");
        getContentPane().add(loadedImage);
        loadedImage.setBounds(90, 220, 690, 430);

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Load.png"))); // NOI18N
        btnLoad.setToolTipText("Load Image");
        btnLoad.setSize(new java.awt.Dimension(60, 60));
        getContentPane().add(btnLoad);
        btnLoad.setBounds(20, 450, 60, 60);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Exit.png"))); // NOI18N
        btnExit.setToolTipText("Load Image");
        btnExit.setPreferredSize(new java.awt.Dimension(60, 60));
        btnExit.setSize(new java.awt.Dimension(60, 60));
        getContentPane().add(btnExit);
        btnExit.setBounds(20, 590, 60, 60);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Save.png"))); // NOI18N
        btnSave.setToolTipText("Save Image");
        btnSave.setPreferredSize(new java.awt.Dimension(60, 60));
        btnSave.setSize(new java.awt.Dimension(60, 60));
        getContentPane().add(btnSave);
        btnSave.setBounds(20, 380, 60, 60);

        btnLibrary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Picture.png"))); // NOI18N
        btnLibrary.setToolTipText("Library");
        btnLibrary.setPreferredSize(new java.awt.Dimension(60, 60));
        btnLibrary.setSize(new java.awt.Dimension(60, 60));
        getContentPane().add(btnLibrary);
        btnLibrary.setBounds(20, 520, 60, 60);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/bg1.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 820, 680);

        setBounds(0, 0, 800, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG y PNG","jpg","png");
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try{
                File file = fc.getSelectedFile();
                this.icon = new ImageIcon(file.toString());
                Icon img = new ImageIcon(this.icon.getImage().getScaledInstance(this.background.getWidth(), this.background.getHeight(), Image.SCALE_DEFAULT));
                loadedImage.setText(null);
                loadedImage.setIcon( img );

            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Error opening the image "+ ex); 
            }
        net.Image image = new net.Image("Image 1", 0, "1");
        image.setStatus("Client");
        clientController.setImage(image);
        clientController.setTarget_ip("localhost");    
        clientController.sendImage();    
        clientController.receiveImages();
    }//GEN-LAST:event_btnAddActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    static int port;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUIOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUIOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUIOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUIOld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         //port = Integer.parseInt(args[0]);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUIOld().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLibrary;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel loadedImage;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        
    }
}

