 /* Copyright (C) 2015 carcasti
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.client.ui;


import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author carcasti
 */
public class ClientUI extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ClientUI
     */
    JButton b1;
    JLabel l1;
    JFileChooser fc;
   
    public ClientUI() {
        initComponents();
        fc = new JFileChooser();
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jButton3.addActionListener(this);
        jButton4.addActionListener(this);
 
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Filter Express");
        setName("clienteUiForm"); // NOI18N
        setSize(new java.awt.Dimension(650, 600));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Exit.png")));
        jButton1.setToolTipText("Exit");
        jButton1.setActionCommand("btnExit");
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 460, 85, 80);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Load.png")));
        jButton2.setToolTipText("Load image");
        jButton2.setActionCommand("btnLoad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 460, 85, 80);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Modify.png")));
        jButton3.setToolTipText("Edit Image");
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 460, 85, 80);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/Search.png")));
        jButton4.setToolTipText("Search Image");
        jButton4.setActionCommand("btnSearch");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(180, 460, 85, 80);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/client/ui/images/image1.jpg")));
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 650, 600);

        setBounds(0, 0, 650, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_jButton4ActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jButton4) {
            FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG y PNG","jpg","png");
            fc.setFileFilter(filter);
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                try{
                    File file = fc.getSelectedFile();
                    EditorUI editor = new EditorUI();
                    editor.setVisible(true);
                    editor.icon = new ImageIcon(file.toString());
                    Icon img = new ImageIcon(editor.icon.getImage().getScaledInstance(editor.jLabel1.getWidth(), editor.jLabel1.getHeight(), Image.SCALE_DEFAULT));
                    editor.jLabel1.setText(null);
                    editor.jLabel1.setIcon( img );

                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Error opening the image "+ ex); 
                }
                //This is where a real application would open the file.    
            } 
        if (e.getSource() == jButton1) {}
        if (e.getSource() == jButton2) {}
        if (e.getSource() == jButton3) {}
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}

